name: bridges_load
description: A new Flutter project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.2.0"

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: any
  flutter_spinkit: any

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
